# Generated by Django 5.2.9 on 2025-12-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_consultationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ad_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='upload_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
