# Generated by Django 5.2.9 on 2025-12-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='as_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_as_approved',
            field=models.BooleanField(default=False),
        ),
    ]
