# Generated by Django 5.2.9 on 2025-12-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_as_reason_customer_is_as_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
    ]
