# Generated by Django 5.2.9 on 2025-12-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='detail_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
