# Generated by Django 5.2.9 on 2025-12-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_customstatus_alter_consultationlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='전화번호 (고유값)'),
        ),
    ]
