# Generated by Django 5.2.9 on 2025-12-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstatus',
            name='status',
            field=models.CharField(max_length=50, verbose_name='커스텀 상태명'),
        ),
    ]
