# Generated by Django 5.2.9 on 2025-12-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_customstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='agent_policy',
            field=models.IntegerField(default=0, verbose_name='상담사 입력 정책금(단위:만원)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='policy_amt',
            field=models.IntegerField(default=0, verbose_name='본사 확정 정책금(단위:만원)'),
        ),
    ]
