# Generated by Django 5.2.9 on 2025-12-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_customer_agent_policy_alter_customer_policy_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='settlement_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='정산예정일'),
        ),
    ]
