# Generated by Django 5.2.9 on 2025-12-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_customer_settlement_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='정산 상태명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='settlement_status',
            field=models.CharField(blank=True, default='미정산', max_length=50, verbose_name='정산 상태'),
        ),
    ]
