# Generated by Django 5.2.9 on 2025-12-22 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_settlementstatus_customer_settlement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('INTERNET', '인터넷'), ('TV', 'TV'), ('STB', '셋탑박스'), ('MOBILE', '모바일/기타')], max_length=20, verbose_name='카테고리')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
            ],
        ),
        migrations.AlterModelOptions(
            name='consultationlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='usim_info',
        ),
        migrations.RemoveField(
            model_name='customstatus',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='consultationlog',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consultationlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='consultationlog',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ad_cost',
            field=models.IntegerField(default=0, verbose_name='광고비'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='agent_policy',
            field=models.IntegerField(default=0, verbose_name='상담사 입력 정책금'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='as_reason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='callback_schedule',
            field=models.DateTimeField(blank=True, null=True, verbose_name='재통화 예정'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='detail_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='실패 사유'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_as_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_memo',
            field=models.TextField(blank=True, default='', verbose_name='최근 메모'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='통신사'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='policy_amt',
            field=models.IntegerField(default=0, verbose_name='본사 확정 정책금'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rank',
            field=models.IntegerField(default=1, verbose_name='중요도'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='support_amt',
            field=models.IntegerField(default=0, verbose_name='지원금'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='DB 업로드일'),
        ),
        migrations.AlterField(
            model_name='customstatus',
            name='status',
            field=models.CharField(max_length=50, unique=True, verbose_name='커스텀 상태명'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='플랫폼명'),
        ),
        migrations.AlterField(
            model_name='settlementstatus',
            name='status',
            field=models.CharField(max_length=50, unique=True, verbose_name='정산 상태명'),
        ),
    ]
