# Generated by Django 5.2.9 on 2025-12-22 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_salesproduct_alter_consultationlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationlog',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='customer',
            name='additional_info',
            field=models.TextField(blank=True, default='', verbose_name='후처리/특이사항'),
        ),
        migrations.AddField(
            model_name='customer',
            name='checklist',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='체크리스트'),
        ),
        migrations.AddField(
            model_name='customer',
            name='usim_info',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='유심 정보'),
        ),
        migrations.AddField(
            model_name='customstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultationlog',
            name='content',
            field=models.TextField(verbose_name='상담 내용'),
        ),
        migrations.AlterField(
            model_name='consultationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일시 (자동 타임스탬프)'),
        ),
        migrations.AlterField(
            model_name='consultationlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sales.customer', verbose_name='관련 고객'),
        ),
        migrations.AlterField(
            model_name='consultationlog',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ad_cost',
            field=models.IntegerField(default=0, verbose_name='적용 광고비(단위:원)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='agent_policy',
            field=models.IntegerField(default=0, verbose_name='상담사 입력 정책금(단위:만원)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='as_reason',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='AS 요청 사유'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='callback_schedule',
            field=models.DateTimeField(blank=True, null=True, verbose_name='재통화 예정일시'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='데이터 생성일시'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='detail_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='실패/취소 상세 사유'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_as_approved',
            field=models.BooleanField(default=False, verbose_name='AS 승인 여부'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_memo',
            field=models.TextField(blank=True, default='', verbose_name='최근 상담 메모 (요약)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_customers', to=settings.AUTH_USER_MODEL, verbose_name='담당 상담사'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='전화번호 (고유값)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='플랫폼(통신사)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='policy_amt',
            field=models.IntegerField(default=0, verbose_name='본사 확정 정책금(단위:만원)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rank',
            field=models.IntegerField(default=1, verbose_name='진성도(중요도, 1~5)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='support_amt',
            field=models.IntegerField(default=0, verbose_name='지원금(단위:만원)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최근 수정일시'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='DB 업로드일 (배정 기준일)'),
        ),
        migrations.AlterField(
            model_name='customstatus',
            name='status',
            field=models.CharField(max_length=50, verbose_name='커스텀 상태명'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='플랫폼명(통신사)'),
        ),
        migrations.AlterField(
            model_name='settlementstatus',
            name='status',
            field=models.CharField(max_length=50, verbose_name='정산 상태명'),
        ),
    ]
