# Generated by Django 5.2.9 on 2025-12-23 04:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_consultationlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, null=True, verbose_name='안드로이드 FCM 토큰'),
        ),
        migrations.AlterField(
            model_name='consultationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consultationlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='consultationlog',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ad_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='additional_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='agent_policy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='as_reason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='callback_schedule',
            field=models.DateTimeField(blank=True, null=True, verbose_name='재통화 예정일'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checklist',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='detail_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='installed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_as_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_memo',
            field=models.TextField(blank=True, default='', verbose_name='최근 메모'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='플랫폼'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='policy_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='product_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rank',
            field=models.IntegerField(default=1, verbose_name='진성도'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='settlement_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='settlement_status',
            field=models.CharField(blank=True, default='미정산', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='support_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='DB 업로드일'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='usim_info',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='문자 내용')),
                ('status', models.CharField(choices=[('PENDING', '발송대기'), ('SUCCESS', '발송성공'), ('FAIL', '발송실패')], default='PENDING', max_length=10, verbose_name='상태')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송 시간')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='발신 상담사')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer', verbose_name='수신 고객')),
            ],
        ),
    ]
