# Generated by Django 5.2.9 on 2025-12-24 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_salesproduct_created_at_smslog_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='smslog',
            name='direction',
            field=models.CharField(choices=[('OUT', '발신 (PC->고객)'), ('IN', '수신 (고객->PC)')], default='OUT', max_length=5, verbose_name='방향'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='담당 상담사'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='sales.customer', verbose_name='수신 고객'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('PENDING', '발송대기'), ('SUCCESS', '전송성공'), ('FAIL', '전송실패'), ('RECEIVED', '수신완료')], default='PENDING', max_length=10, verbose_name='상태'),
        ),
    ]
