# Generated by Django 5.2.9 on 2026-01-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_adchannel_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='request_message',
            field=models.TextField(blank=True, help_text='관리자가 보낸 확인 요청 메시지', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='request_status',
            field=models.CharField(blank=True, default=None, help_text='REQUESTED(요청됨), PROCESSING(처리중), COMPLETED(완료)', max_length=20, null=True),
        ),
    ]
