# Generated by Django 5.2.9 on 2026-01-09 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_customer_request_message_customer_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('KT', 'KT'), ('SK', 'SK'), ('LG', 'LG'), ('Sky', 'Sky')], max_length=10)),
                ('image', models.ImageField(upload_to='policy_images/', verbose_name='정책 이미지')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_important', models.BooleanField(default=False, verbose_name='중요 공지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
