# Generated by Django 5.2.9 on 2026-01-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_todotask'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sms_images/'),
        ),
    ]
