# Generated by Django 5.2.9 on 2026-01-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_smslog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
