# Generated by Django 5.2.9 on 2026-01-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_client_customer_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='settlement_memo',
            field=models.TextField(blank=True, null=True, verbose_name='정산 메모'),
        ),
    ]
