# Generated by Django 5.2.9 on 2026-01-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_customer_settlement_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='settlement_complete_date',
            field=models.DateField(blank=True, null=True, verbose_name='정산 완료일'),
        ),
    ]
